config/routes.rb
Rails.application.routes.draw do

  root :to => 'gossips#index'

  get '/static_pages/team', to: 'static_pages#team'

  get '/static_pages/contact', to: 'static_pages#contact'

  resources :gossips

  resources :cities

  resources :users
  
  resources :sessions, only:[:new, :create, :destroy]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
    has_many :users

    # validates :name, :zip_code, presence: true
    validates :zip_code, length: {in:3..16}
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :gossip
    has_many :likes
  
  
    validates :content, length: {maximum: 285}
end

app/models/gossip.rb
class Gossip < ApplicationRecord
    belongs_to :user
    has_many :join_tag_gossips
    has_many :tags, through: :join_tag_gossips
    has_many :comments, dependent: :destroy
    has_many :likes, dependent: :destroy
  
  
    validates :title, length: {in: 3..16}
    validates :content, :user, presence: true
end

app/models/join_message_recipient.rb
class JoinMessageRecipient < ApplicationRecord
    belongs_to :recipient, class_name: "User"
    belongs_to :private_message
end

app/models/join_tag_gossip.rb
class JoinTagGossip < ApplicationRecord
    belongs_to :tag, optional:true
    belongs_to :gossip
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :gossip, optional: true
    belongs_to :comment, optional: true
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
    belongs_to :sender, class_name: "User"
    has_many :join_message_recipients
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :join_tag_gossips
    has_many :gossips, through: :join_tag_gossips
  
    validates :title, length: {maximum: 50}
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    belongs_to :city, optional: true
    has_many :gossips, dependent: :destroy
    has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
    has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
    has_many :comments, dependent: :destroy
    has_many :likes, dependent: :destroy
  
    validates :password, :email, presence: true
    validates :password, length: {minimum: 6}
    validates :description, length: {maximum: 500}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    include ApplicationHelper

end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def show
   
    @city = City.find(params[:id])
    @city_gossips = []
    Gossip.all.each do |gossip|
       if gossip.user.city_id == @city.id
        @city_gossips << gossip
       end
    end
  end

  def new
  end

  def create
  end

  def index
  end

  def delete
  end

  def edit
  end

  def update
  end

end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
include SessionsHelper
before_action :authenticate_user, except: [:index]

  def index
    @gossips = Gossip.all
  end

  def show
    @gossip = Gossip.find(params[:id])
    @user = @gossip.user
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])

    if current_user == @gossip.user
      @gossip.update(gossip_params)
      redirect_to gossip_path
    else
      flash.alert = "Vous n'êtes pas l'auteur de ce gossip !"
      redirect_to gossips_path
    end
    
  end

  def new
    @gossip = Gossip.new
  end

  def create
     @gossip = Gossip.new(user: current_user, title: params[:title],content: params[:content])

     if @gossip.save
      redirect_to gossips_path, notice: "Tu as créé un nouveau potin."

    else
      render :new
      flash.alert = "Il y a un problème, recommence"
    end

  end

  def destroy
    @gossip = Gossip.find(params[:id])
    if current_user == @gossip.user
    
      if @gossip.destroy
        redirect_to gossips_path
  
      else
        render :edit
        flash.alert = "Il y a un problème, recommence"
      end

    else
      flash.alert = "Vous n'êtes pas l'auteur de ce gossip !"
      redirect_to gossips_path
    end
    

  end

  private

  def gossip_params

    params.require(:gossip).permit(:title, :content)

  end

  def authenticate_user
    
    unless current_user
      flash.alert = "Vous devez être connecté"
      redirect_to new_session_path
    end
    
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
include SessionsHelper

  def new
    @user = User.new
  end

  def create
    # cherche s'il existe un utilisateur en base avec l'e-mail
    user = User.find_by(email: params[:email])
    # on vérifie si l'utilisateur existe bien ET si on arrive à l'authentifier (méthode bcrypt) avec le mot de passe
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to gossips_path, notice: "Bienvenue #{User.find_by(id: session[:user_id]).first_name}!"
      # redirige où tu veux, avec un flash ou pas
    else
      flash.alert = "Utilisateur ou mot de passe incorrect!"
      @user = User.new
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to :gossips
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
include SessionsHelper

  def index
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new(first_name: params[:first_name], last_name: params[:last_name], description: params[:description], email: params[:email], age: params[:age], password: params[:password], city_id: rand(1..5))
   end

  def create
    @user = User.new(first_name: params[:first_name], last_name: params[:last_name], description: params[:description], email: params[:email], age: params[:age], password: params[:password],city_id: rand(1..5))

    if @user.save
      redirect_to gossips_path, notice: "Bienvenue, nouvel utilisateur !"
    else
      render 'new'
      flash.alert = "Il y a un problème, recommence"
    end
  end

  def delete
  end

  def edit
  end

  def update
  end

private

  def user_params
    User.new(first_name: params[:first_name], last_name: params[:last_name], description: params[:description], email: params[:email], age: params[:age], password: params[:password])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

    def flash_class(level)
        case level
            when 'notice'
              "alert alert-primary"
            when 'success'
              "alert alert-success"
            when 'error'
              "alert alert-danger"
            when 'alert'
              "alert alert-danger"
        end
    end
        
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    def current_user
        User.find_by(id: session[:user_id])
    end

    def log_in(user)
        session[:user_id] = user.id
    end

    def logged_in?
        
        if current_user
            return true
        else 
            return false
        end

    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cities/create.html.erb
<h1>Cities#create</h1>
<p>Find me in app/views/cities/create.html.erb</p>

app/views/cities/delete.html.erb
<h1>Cities#delete</h1>
<p>Find me in app/views/cities/delete.html.erb</p>

app/views/cities/edit.html.erb
<h1>Cities#edit</h1>
<p>Find me in app/views/cities/edit.html.erb</p>

app/views/cities/index.html.erb
<h1>Cities#index</h1>
<p>Find me in app/views/cities/index.html.erb</p>

app/views/cities/new.html.erb
<h1>Cities#new</h1>
<p>Find me in app/views/cities/new.html.erb</p>

app/views/cities/show.html.erb
<div class="container">
    <h1>Ville : <%= @city.name%> </h1>
    <div class="album py-5 ">
        <div class="row">
        <% @city_gossips.each do |gossip| %>
            <div class="col-md-4">
            <div class="card" style="width: 80%;">
                <div class="card-body">
                <h5 class="card-title"><%=gossip.title%></h5>
                <h6 class="card-subtitle mb-2 text-muted">By <%=gossip.user.first_name%></h6>
                <p class="card-text"><%=gossip.content%></p>
                <a href="#" class="card-link"><%= link_to "Read more", gossip_path(gossip.id) %></a>
                </div>
            </div>
            <br>
            </div>
        <% end %>
        </div>  
    </div>
</div>

app/views/cities/update.html.erb
<h1>Cities#update</h1>
<p>Find me in app/views/cities/update.html.erb</p>

app/views/gossips/create.html.erb
<h1>Gossip#create</h1>
<p>Find me in app/views/gossip/create.html.erb</p>

app/views/gossips/destroy.html.erb
<h1>Gossip#destroy</h1>
<p>Find me in app/views/gossip/destroy.html.erb</p>

app/views/gossips/edit.html.erb
 <% flash.each do |key, msg| %>

    <div class="<%= flash_class(key) %>" role="alert">
    <%= msg %>

    </div>

<% end %>
    <div class="container mt-5 form-group">
        <div class= "bg-light container fieldset mt-3 mr3 pt-3 fieldset col-lg-4 ">
            <h1 class="text-center border-bottom">Editer le gossip</h1>
                <br>
                <%= form_for @gossip do |f|%>

                    <div class="form-group">

                        <label>Titre :</label>

                        <%= f.text_field :title%>

                        <br>
                        <br>

                        <label>Contenu :</label>

                        <%= f.text_area :content%>

                    </div>
                    <div class="form-group text-center">

                        <button type="submit" class="btn btn-primary">Modifier</button>

                    </div>

                <% end %>
        </div>
    </div>

app/views/gossips/index.html.erb
<header role="main">
     <!-- Main jumbotron for a primary marketing message or call to action -->
     <div class="jumbotron" style="background-image: url(https://images.pexels.com/photos/568025/pexels-photo-568025.jpeg?cs=srgb&dl=black-and-white-black-and-white-depressed-depression-568025.jpg&fm=jpg); background-size: 100%;">
       <div class="container">
         <h1 class="display-3 text-jumbo text-black">Bienvenue sur The Gossip Project</h1>
         <br>
         <p class="text-jumbo text-black font-weight-bold">Le site des potins de THP, réalisé par la team Toulouse</p>
       </div>
     </div>
</header>

<div>

    <br>

    <div class="text-center mt-3 ">

         <%= link_to "Créer un gossip", new_gossip_path, class: "btn btn-success btn-lg"%>

    </div>

    <br>

    <div class="album py-5 container">
        <div class="row">
        <% @gossips.reverse_each do |gossip| %>

            <div class="col-md-4">
            <div class="card bg-light" style="width: 80%;">
                <div class="card-body text-center">

                <h5 class="card-title">Gossip n°<%= gossip.id%></h5>
                <hr>
                <h6 class="card-subtitle mb-2 font-weight-bold">Titre: <%= gossip.title%></h6>

                <p class="card-text text-muted "><%= gossip.user.first_name %></p>

                <%= link_to "Voir le gossip", gossip_path(gossip.id), class: "btn btn-primary"%>
                
                </div>
            </div>
            <br>
            </div>

        <% end %>
        </div>
    </div>
</div>

app/views/gossips/new.html.erb
 <% flash.each do |key, msg| %>

    <<div class="<%= flash_class(key) %>" role="alert">

    <%= msg %>

    </div>

<% end %>

<div class="container mt-5 form-group">
    <div class= "bg-light container fieldset mt-3 mr3 pt-3 fieldset col-lg-4 ">
        <h1 class="text-center border-bottom">Créer un gossip</h1>
        <br>


        <%= form_tag url_for(action: 'create'), method: "post" do %>
        
            <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
            

            <%= text_field_tag 'title', @gossip.title, class:"form-control", placeholder: "Titre" %>

            <br>


            <%= text_area_tag 'content', @gossip.content, class:"form-control", placeholder: "Contenu du gossip"  %>

            <br>

            <div class="form-group text-center">

                 <button type="submit" class="btn btn-lg btn-success">Créer</button>
            
            </div>

        <% end %>
    </div>

app/views/gossips/show.html.erb
<div class="container mt-5 form-group">
    <div class= "bg-light container fieldset mt-3 mr3 pt-3 fieldset col-lg-4 ">
    <h1 class="text-center border-bottom"><%= @gossip.title %></h1>
    <br>
    <p>"<%= @gossip.content%>"</p>

    <p>Auteur : <a href="<%= user_path(@user.id)%>"><%= @gossip.user.last_name%> <%= @gossip.user.first_name%></a>
    <p>

        
        <%= link_to "Retourner aux gossips", gossips_path, class: "btn btn-primary"%>
        <%= link_to "Editer", edit_gossip_path(@gossip.id), class: "btn btn-sm btn-outline-secondary"%>
       

        <%= link_to "Supprimer", gossip_path(@gossip.id), class:"btn btn-sm btn-outline-danger", data:{confirm:"Etes vous sûr de vouloir supprimer ce potin ?", method:"DELETE"} %>

    </p>
    </div>
</div>

app/views/gossips/update.html.erb
<h1>Gossip#update</h1>
<p>Find me in app/views/gossip/update.html.erb</p>

app/views/static_pages/contact.html.erb
<section class="contact-section bg-light container fieldset mt-5 mr3 pt-3 fieldset ">

    <h1 class="border-bottom text-center"> Contactez-nous </h1>
    <br>
  <div class="card">

    
    <div class="row">

      
      <div class="col-lg-8">

        <div class="card-body form">

          <h3 class="mt-4 text-center"><i class="fas fa-envelope pr-2"></i>Ecrivez-nous !</h3>
          <br>

          <div class="row">
            
            <div class="col-md-6">
              <div class="md-form mb-0">
                <input type="text" id="form-contact-name" class="form-control", placeholder="Nom">
                <label> </label>
              </div>
            </div>
                
            <div class="col-md-6">
              <div class="md-form mb-0">
                <input type="text" id="form-contact-email" class="form-control", placeholder="Email">
                <label> </label>
              </div>
            </div>
          </div>
          
          <div class="row">
            
            <div class="col-md-6">
              <div class="md-form mb-0">
                <input type="text" id="form-contact-phone" class="form-control", placeholder="Téléphone">
                <label> </label>
              </div>
            </div>
            
            <div class="col-md-6">
              <div class="md-form mb-0">
                <input type="text" id="form-contact-company" class="form-control", placeholder="Entreprise">
                <label> </label>
              </div>
            </div>
        
          </div>
          
          <div class="row">

            <div class="col-md-12">
              <div class="md-form mb-0">
                <textarea id="form-contact-message" class="form-control md-textarea" rows="3" placeholder="Message"></textarea>
                <a href="mailto:thp.toulouse@gmail.com"class="btn-floating btn-lg text-dark">
                    Envoyer
                  <i class="far fa-paper-plane text-dark"></i>
                </a>
              </div>
            </div>
          </div>
        
        </div>

      </div>
          
      <div class="col-lg-4">

        <div class="card-body contact text-center h-100 white-text">

          <h3 class="my-4 pb-2">Contact</h3>
          <br>
          <hr class="hr-light my-4">
          <ul class="text-lg-left list-unstyled ml-4">
            <li>
              <p><i class="fas fa-map-marker-alt pr-2"></i>Toulouse, 31000</p>
            </li>
            <li>
              <p><i class="fas fa-phone pr-2"></i>06 12 34 56 78</p>
            </li>
            <li>
              <p><i class="fas fa-envelope pr-2"></i>thp.toulouse@gmail.com</p>
            </li>
          </ul>
          <hr class="hr-light my-4">
        </div>

      </div>

    </div>

  </div>

</section>

app/views/static_pages/team.html.erb
<section class="bg-light container fieldset mb-5 mt-5 mr3 pt-3 fieldset  ">

  <h1 class="text-center border-bottom ">La Team THP Toulouse</h1>

  <div class="row text-center">

    <div class="col-md-4 mb-md-0 mb-5">
      <div class="avatar mx-auto">
        <img src="/assets/Nathan.jpg" class="img-thumbnail z-depth-1-half" alt="Sample avatar" style="width:80%">
      </div>
      <h4 class="font-weight-bold dark-grey-text my-4">😇 Nathan Château</h4>
      
       <!--Email-->
      <a href="mailto:nathanchateau@gmail.com" type="button" class="btn-floating btn-lg mx-1 mb-0 btn-email">
        <i class="fas fa-envelope text-dark"></i>
      </a>
      <!-- GitHub-->
      <a type="button" class="btn-floating btn-lg mx-1 mb-0 btn-git">
        <i class="fab fa-github text-dark"></i>
      </a>
    </div>
    <!-- Grid column -->

    <!-- Grid column -->
    <div class="col-md-4 mb-md-0 mb-5">
      <div class="avatar">
        <img src="/assets/Amy.jpg" class="img-thumbnail z-depth-1-half" alt="Sample avatar" style="width:80%">
      </div>
      <h4 class="font-weight-bold dark-grey-text my-4">😻 Amy McArthur</h4>
     
      <!--Email-->
      <a href="mailto:amymcarthur10@gmail.com" type="button" class="btn-floating btn-lg mx-1 mb-0 btn-email">
        <i class="fas fa-envelope text-dark"></i>
      </a>
     
      <!-- GitHub-->
      <a type="button" class="btn-floating btn-lg mx-1 mb-0 btn-git">
        <i class="fab fa-github text-dark"></i>
      </a>
    </div>
    <!-- Grid column -->

    <!-- Grid column -->
    <div class="col-md-4">
      <div class="avatar mx-auto">
        <img src="/assets/Hadrien.jpg" class="img-thumbnail z-depth-1-half" alt="Sample avatar" style="width:80%">
      </div>
      <h4 class="font-weight-bold dark-grey-text my-4">❤️ Hadrien Samouillan</h4>
      
      <!--Email-->
        <a href="mailto:adrien.samouillan@gmail.com" type="button" class="btn-floating btn-lg mx-1 mb-0 btn-email">
        <i class="fas fa-envelope text-dark"></i>
        </a>
        
      <!-- GitHub-->
      <a type="button" class="btn-floating btn-lg mx-1 mb-0 btn-git">
        <i class="fab fa-github text-dark"></i>
      </a>
    </div>

  </div>

</section>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/delete.html.erb
<h1>Users#delete</h1>
<p>Find me in app/views/users/delete.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
 <% flash.each do |key, msg| %>

    <div class="<%= flash_class(key) %>" role="alert">

    <%= msg %>

    </div>

<% end %>

<div class="container mt-5 form-group">

    <div class= "bg-light container fieldset mt-3 mr3 pt-3 fieldset col-lg-4 ">
    
        <h1 class="text-center">Inscription</h1>
        <p class="border-bottom">
        
        <%= form_tag url_for(action: 'create'), method: "post" do %>


            <%= text_field_tag 'first_name', @user.first_name, class: "form-control", placeholder: "Prénom" %>

            <br>

            <%= text_field_tag 'last_name', @user.last_name, class: "form-control", placeholder: "Nom" %>

            <br>

            <%= text_field_tag 'email', @user.email, class: "form-control", placeholder: "Email" %>

            <br>

            <%= password_field_tag 'password', @user.password, class: "form-control", placeholder: "Mot de passe" %>

            <br>

            <div class="form-group">

            <button type="submit" class="float-right btn btn-success">Créer</button>

        </div>

    <% end %>

    </div>
</div>
    

app/views/users/show.html.erb
<div class="">
<div class="ml-4 mt-4 mb-4">
    <div class="card bg-light flex-row flex-wrap" style="width: 600px;">
        <div class="card-header border-0 bg-light">
            <img class="card-img-top img-thumbnail" src="https://images.pexels.com/photos/1446948/pexels-photo-1446948.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=150&w=200" alt="Card image cap">
        </div>
        <div class="bg-light">
            <br/><br/>
            <h5 class="card-title font-weight-bold"><%= @user.first_name%> <%= @user.last_name%></h5>
                <br>
                <p class="card-text text-body"><strong>Email :</strong> <%= @user.email %></p>
                <p class="card-text text-body"><strong>Description :</strong> <%= @user.description %></p>
                <p class="card-text text-body"><strong>Age :</strong> <%= @user.age %> </p>
                <p class="card-text text-body"><strong>Ville :</strong> <%= link_to "#{@user.city.name}", city_path(@user.city), class: "text-secondary" %></p>
        </div>
    </div>
</div>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>