config/routes.rb
Rails.application.routes.draw do

  root :to => 'gossips#index'

  get '/static_pages/team', to: 'static_pages#team'

  get '/static_pages/contact', to: 'static_pages#contact'

  resources :gossips

  resources :cities

  resources :users
  
  resources :sessions, only:[:new, :create, :destroy]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
    has_many :users

    # validates :name, :zip_code, presence: true
    validates :zip_code, length: {in:3..16}
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :gossip
    has_many :likes
  
  
    validates :content, length: {maximum: 285}
end

app/models/gossip.rb
class Gossip < ApplicationRecord
    belongs_to :user
    has_many :join_tag_gossips
    has_many :tags, through: :join_tag_gossips
    has_many :comments, dependent: :destroy
    has_many :likes, dependent: :destroy
  
  
    validates :title, length: {in: 3..16}
    validates :content, :user, presence: true
end

app/models/join_message_recipient.rb
class JoinMessageRecipient < ApplicationRecord
    belongs_to :recipient, class_name: "User"
    belongs_to :private_message
end

app/models/join_tag_gossip.rb
class JoinTagGossip < ApplicationRecord
    belongs_to :tag, optional:true
    belongs_to :gossip
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :gossip, optional: true
    belongs_to :comment, optional: true
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
    belongs_to :sender, class_name: "User"
    has_many :join_message_recipients
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :join_tag_gossips
    has_many :gossips, through: :join_tag_gossips
  
    validates :title, length: {maximum: 50}
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    belongs_to :city, optional: true
    has_many :gossips, dependent: :destroy
    has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
    has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
    has_many :comments, dependent: :destroy
    has_many :likes, dependent: :destroy
  
    validates :password, :email, presence: true
    validates :password, length: {minimum: 6}
    validates :description, length: {maximum: 500}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    include ApplicationHelper

end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def show
   
    @city = City.find(params[:id])
    @city_gossips = []
    Gossip.all.each do |gossip|
       if gossip.user.city_id == @city.id
        @city_gossips << gossip
       end
    end
  end

  def new
  end

  def create
  end

  def index
  end

  def delete
  end

  def edit
  end

  def update
  end

end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
include SessionsHelper
before_action :authenticate_user, except: [:index]

  def index
    @gossips = Gossip.all
  end

  def show
    @gossip = Gossip.find(params[:id])
    @user = @gossip.user
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])

    if current_user == @gossip.user
      @gossip.update(gossip_params)
      redirect_to gossip_path
    else
      flash.alert = "Vous n'êtes pas l'auteur de ce gossip !"
      redirect_to gossips_path
    end
    
  end

  def new
    @gossip = Gossip.new
  end

  def create
     @gossip = Gossip.new(user: current_user, title: params[:title],content: params[:content])

     if @gossip.save
      redirect_to gossips_path, notice: "Tu as créé un nouveau potin."

    else
      render :new
      flash.alert = "Il y a un problème, recommence"
    end

  end

  def destroy
    @gossip = Gossip.find(params[:id])
    if current_user == @gossip.user
    
      if @gossip.destroy
        redirect_to gossips_path
  
      else
        render :edit
        flash.alert = "Il y a un problème, recommence"
      end

    else
      flash.alert = "Vous n'êtes pas l'auteur de ce gossip !"
      redirect_to gossips_path
    end
    

  end

  private

  def gossip_params

    params.require(:gossip).permit(:title, :content)

  end

  def authenticate_user
    
    unless current_user
      flash.alert = "Vous devez être connecté"
      redirect_to new_session_path
    end
    
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
include SessionsHelper

  def new
    @user = User.new
  end

  def create
    # cherche s'il existe un utilisateur en base avec l'e-mail
    user = User.find_by(email: params[:email])
    # on vérifie si l'utilisateur existe bien ET si on arrive à l'authentifier (méthode bcrypt) avec le mot de passe
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to gossips_path, notice: "Bienvenue #{User.find_by(id: session[:user_id]).first_name}!"
      # redirige où tu veux, avec un flash ou pas
    else
      flash.alert = "Utilisateur ou mot de passe incorrect!"
      @user = User.new
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to :gossips
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
include SessionsHelper

  def index
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new(first_name: params[:first_name], last_name: params[:last_name], description: params[:description], email: params[:email], age: params[:age], password: params[:password], city_id: rand(1..5))
   end

  def create
    @user = User.new(first_name: params[:first_name], last_name: params[:last_name], description: params[:description], email: params[:email], age: params[:age], password: params[:password],city_id: rand(1..5))

    if @user.save
      redirect_to gossips_path, notice: "Bienvenue, nouvel utilisateur !"
    else
      render 'new'
      flash.alert = "Il y a un problème, recommence"
    end
  end

  def delete
  end

  def edit
  end

  def update
  end

private

  def user_params
    User.new(first_name: params[:first_name], last_name: params[:last_name], description: params[:description], email: params[:email], age: params[:age], password: params[:password])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

    def flash_class(level)
        case level
            when 'notice'
              "alert alert-primary"
            when 'success'
              "alert alert-success"
            when 'error'
              "alert alert-danger"
            when 'alert'
              "alert alert-danger"
        end
    end
        
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    def current_user
        User.find_by(id: session[:user_id])
    end

    def log_in(user)
        session[:user_id] = user.id
    end

    def logged_in?
        
        if current_user
            return true
        else 
            return false
        end

    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  <link href="//netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">

  <script src="https://kit.fontawesome.com/f1d8fe4e09.js" crossorigin="anonymous"></script>

    <title>GossipProject</title>
  </head>

  <body>

      <% flash.each do |key, msg| %>
     <div class="<%= flash_class(key) %>" role="alert">
      <%= msg %>
      </div>
      <% end %>

    <nav class="navbar navbar-expand-lg sticky-top navbar-light bg-light border-bottom ">
     <%= link_to "The Gossip Project", gossips_path, class: "navbar-brand"%>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
        <li class="nav-item">
            <%= link_to "Accueil", gossips_path, class: "nav-link"%>
        </li>
        <li class="nav-item">
            <%= link_to "Team", static_pages_team_path, class: "nav-link"%>
        </li>
        <li class="nav-item">
            <%= link_to "Contact", static_pages_contact_path, class: "nav-link"%>
        </li>
	</ul>

		<div class="btn-group">

		<button type="button" class="btn btn-light dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			<span class="sr-only ">Toggle Dropdown</span>
		</button>
		
		<div class="dropdown-menu bg-light">
			<% if logged_in? %>
					
						<li class="nav-item">
							<%= link_to "#{current_user.first_name}", user_path(current_user.id), class:"nav-link text-primary text-uppercase"%>
						</li>
						<li class="nav-item">
							<%= link_to "Se déconnecter", session_path(session.id), class:"nav-link text-danger", method: :delete %>
						</li>
					
						<% else %>
					
						<li class="nav-item">
							<%= link_to "Se connecter", new_session_path, class: "nav-link text-primary"%>
						</li>
						<li class="nav-item">
							<%= link_to "S'inscrire", new_user_path, class: "nav-link text-success"%>
						</li>
					
						<% end %>
		</div>
		</div>

       
    </nav>

	<!-- Optional JavaScript -->
	<!-- jQuery first, then Popper.js, then Bootstrap JS -->
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

    <%= yield %>
    
  </body>
</html>